version: "3.9"

services:
  
  postgres_test:
    image: postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: app_test
    ports:
      - "5433:5432"


  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flor_app:
    build: .
    container_name: flor_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./images:/app/storage/images

  nginx:
    image: nginx:alpine
    container_name: flor_nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/app/storage/images
    depends_on:
      - flor_app


volumes:
  pgdata:
  
